### ISSUE TITLE
Type error when clicking open job logs

### ISSUE THREAD

**Issue by FPtje** [FPtje/vscode-semaphore-ci#6]
```
[2022-07-01 17:50:32.934] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'parent')
	at openJobLogs (/home/falco/.vscode/extensions/fptje.semaphoreci-0.1.1/out/extension.js:401:37)
	at o._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:62521)
	at o.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:63225)
	at s._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:13828)
	at s._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:13512)
	at s._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:12173)
	at s._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:11046)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:86:8949
	at g.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at b.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at a.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:34863
	at g.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at b.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at a.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)
	at r._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23606)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21140
	at g.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at b.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at v.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15856)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14986
	at Socket.R (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:13798)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23) semaphore-ci.openLogs {"value":"fptje.semaphoreci","_lower":"fptje.semaphoreci"}
```

Not sure which situation triggers this.

**Comment by FPtje** [comment]
It turns out this error is thrown when issue #5 happens. Closing as duplicate.
